/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as OpportunityIdRouteImport } from './routes/opportunity.$id'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as OrganizerApplicationsRouteImport } from './routes/organizer.applications'
import { Route as OrganizerNewRouteImport } from './routes/organizer.new'
import { Route as OrganizerOpportunitiesRouteImport } from './routes/organizer.opportunities'
import { Route as OrganizerEditIdRouteImport } from './routes/organizer.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityIdRoute = OpportunityIdRouteImport.update({
  id: '/opportunity/$id',
  path: '/opportunity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerApplicationsRoute = OrganizerApplicationsRouteImport.update({
  id: '/organizer/applications',
  path: '/organizer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerNewRoute = OrganizerNewRouteImport.update({
  id: '/organizer/new',
  path: '/organizer/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerOpportunitiesRoute = OrganizerOpportunitiesRouteImport.update({
  id: '/organizer/opportunities',
  path: '/organizer/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEditIdRoute = OrganizerEditIdRouteImport.update({
  id: '/organizer/edit/$id',
  path: '/organizer/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/organizer/applications': typeof OrganizerApplicationsRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/opportunities': typeof OrganizerOpportunitiesRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/organizer/edit/$id': typeof OrganizerEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/organizer/applications': typeof OrganizerApplicationsRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/opportunities': typeof OrganizerOpportunitiesRoute
  '/organizer': typeof OrganizerIndexRoute
  '/organizer/edit/$id': typeof OrganizerEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/organizer/applications': typeof OrganizerApplicationsRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/opportunities': typeof OrganizerOpportunitiesRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/organizer/edit/$id': typeof OrganizerEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/profile'
    | '/saved'
    | '/opportunity/$id'
    | '/organizer/applications'
    | '/organizer/new'
    | '/organizer/opportunities'
    | '/organizer/'
    | '/organizer/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/profile'
    | '/saved'
    | '/opportunity/$id'
    | '/organizer/applications'
    | '/organizer/new'
    | '/organizer/opportunities'
    | '/organizer'
    | '/organizer/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/profile'
    | '/saved'
    | '/opportunity/$id'
    | '/organizer/applications'
    | '/organizer/new'
    | '/organizer/opportunities'
    | '/organizer/'
    | '/organizer/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  OpportunityIdRoute: typeof OpportunityIdRoute
  OrganizerApplicationsRoute: typeof OrganizerApplicationsRoute
  OrganizerNewRoute: typeof OrganizerNewRoute
  OrganizerOpportunitiesRoute: typeof OrganizerOpportunitiesRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerEditIdRoute: typeof OrganizerEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$id': {
      id: '/opportunity/$id'
      path: '/opportunity/$id'
      fullPath: '/opportunity/$id'
      preLoaderRoute: typeof OpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/applications': {
      id: '/organizer/applications'
      path: '/organizer/applications'
      fullPath: '/organizer/applications'
      preLoaderRoute: typeof OrganizerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/new': {
      id: '/organizer/new'
      path: '/organizer/new'
      fullPath: '/organizer/new'
      preLoaderRoute: typeof OrganizerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/opportunities': {
      id: '/organizer/opportunities'
      path: '/organizer/opportunities'
      fullPath: '/organizer/opportunities'
      preLoaderRoute: typeof OrganizerOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/edit/$id': {
      id: '/organizer/edit/$id'
      path: '/organizer/edit/$id'
      fullPath: '/organizer/edit/$id'
      preLoaderRoute: typeof OrganizerEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  OpportunityIdRoute: OpportunityIdRoute,
  OrganizerApplicationsRoute: OrganizerApplicationsRoute,
  OrganizerNewRoute: OrganizerNewRoute,
  OrganizerOpportunitiesRoute: OrganizerOpportunitiesRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerEditIdRoute: OrganizerEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
